
on: [pull_request]

jobs:
  build-gradle-project:
    name: Build Gradle Project
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-build

      - name: "Gradle: Build"
        uses: ./.github/actions/run-tests
        run: ./gradlew build check

      - name: "Gradle: Publish (Main & Release Only)"
        uses: ./.github/actions/run-tests
        if: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/0.2.1-sovity' }}
        run: ./gradlew publishAllPublicationsToGitHubPackagesRepository ${{ env.GRADLE_ARGS }}
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
