
on: [pull_request]

jobs:
  build-gradle-project:
    name: Build Gradle Project
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-build
      - uses: ./.github/actions/run-tests

      - name: "Gradle: Build"
        run: ./gradlew build check

      - name: "Gradle: Publish (Main & Release Only)"
        run: ./gradlew publishAllPublicationsToGitHubPackagesRepository ${{ env.GRADLE_ARGS }}
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
